[versions]
# Compile only
paper = "1.17-R0.1-SNAPSHOT"
papi = "2.11.2"
bstats = "3.0.0"

#Implementation
triumph-cmds = "1.4.6"

[libraries]
# Compile only
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
papi = { module = "me.clip:placeholderapi", version.ref = "papi" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

#Implementation
# TODO: Upgrade to triumph-cmds 2.0.0
triumph-cmds = { module = "me.mattstudios.utils:matt-framework", version.ref = "triumph-cmds" }